import json

# User-provided classifications (Manufacturer, Model, Type)
classifications = {
    # Log-Periodic
    ("Cushcraft", "ASL201"): "log-periodic",
    ("Titan", "DLP-19"): "log-periodic",
    ("Titan", "LP-8"): "log-periodic",
    ("Titanex", "DLP-10_6"): "log-periodic",
    ("Titanex", "LP-10"): "log-periodic",
    ("Titanex", "LP-1030"): "log-periodic",
    ("Titanex", "LP-11"): "log-periodic",
    ("Titanex", "LP-12"): "log-periodic",
    ("Titanex", "LP-15"): "log-periodic",
    ("Titanex", "LP-1830"): "log-periodic",
    ("Titanex", "LP-5"): "log-periodic",
    ("Titanex", "LP-6"): "log-periodic",
    ("Titanex", "LP-7"): "log-periodic",
    ("Titanex", "LPDA-5"): "log-periodic",
    # Loop
    ("Allgemein", "DeltaLoop 84m"): "loop",
    ("Allgemein", "DeltaLoop120m"): "loop",
    ("Allgemein", "DeltaLoop42m"): "loop",
    ("Magn. Loop", "m-loop162cm"): "loop",
    ("Magn. Loop", "m-loop194cm"): "loop",
    ("Magn. Loop", "m-loop79cm"): "loop",
    ("Magn. Loop", "m-loop825mm"): "loop",
    ("Magn. Loop", "m-loop84cm"): "loop",
    # Quad
    ("Allgemein", "Quad-2El"): "quad",
    ("Allgemein", "Quad-3El"): "quad",
    ("Cubex", "2-El_Cubex"): "quad",
    ("Cubex", "2-El_SpitzCu"): "quad",
    ("Hy-Gain", "2-El_Quad"): "quad",
    ("Wimo", "X-Quad-2"): "quad",
    ("Wimo", "X-Quad-70"): "quad",
    # Vertical
    ("Allgemein", "GP Triple"): "vertical",
    ("Allgemein", "Ringo Range"): "vertical",
    ("Comet", "CX-725"): "vertical",
    ("Comet", "CX-901"): "vertical",
    ("Comet", "CX-902"): "vertical",
    ("Comet", "GP-15"): "vertical",
    ("Comet", "GP-21"): "vertical",
    ("Comet", "GP-3N"): "vertical",
    ("Comet", "GP-91"): "vertical",
    ("Comet", "GP-95"): "vertical",
    ("Comet", "GP-9N"): "vertical",
    ("Cushcraft", "R5"): "vertical",
    ("Cushcraft", "R6000"): "vertical",
    ("Cushcraft", "R6xyz"): "vertical",
    ("Cushcraft", "R7"): "vertical",
    ("Cushcraft", "R7000"): "vertical",
    ("Diamond", "CP5"): "vertical",
    ("Diamond", "DP-CP6"): "vertical",
    ("Diamond", "F-23"): "vertical",
    ("Diamond", "X-200"): "vertical",
    ("Diamond", "X-30"): "vertical",
    ("Diamond", "X-300"): "vertical",
    ("Diamond", "X-4000"): "vertical",
    ("Diamond", "X-50"): "vertical",
    ("Diamond", "X-5000"): "vertical",
    ("Diamond", "X-500H"): "vertical",
    ("Diamond", "X-510N"): "vertical",
    ("Diamond", "X-6000"): "vertical",
    ("Diamond", "X-7000"): "vertical",
    ("Diamond", "X-700H"): "vertical",
    ("Fritzel", "GPA30"): "vertical",
    ("Fritzel", "GPA404"): "vertical",
    ("Fritzel", "GPA50"): "vertical",
    ("Titanex", "GPA80-10"): "vertical",
    # Wire
    ("Allgemein", "Dipol"): "wire",
    ("Allgemein", "G5RV 15m"): "wire",
    ("Allgemein", "G5RV 31m"): "wire",
    ("Allgemein", "W3DZZ"): "wire",
    ("Cushcraft", "D-3-W"): "wire",
    ("Cushcraft", "D-4"): "wire",
    ("Diverse", "Doublet_2x10m"): "wire",
    ("Diverse", "Doublet_2x15m"): "wire",
    ("Diverse", "Doublet_2x20m"): "wire",
    ("Fritzel", "FD3"): "wire",
    ("Fritzel", "FD4"): "wire",
    ("Fritzel", "W3-200"): "wire",
    ("Fritzel", "W3-2000"): "wire",
    ("Langdraht", "LW 100m"): "wire",
    ("Langdraht", "LW 10m"): "wire",
    ("Langdraht", "LW 12m"): "wire",
    ("Langdraht", "LW 14m"): "wire",
    ("Langdraht", "LW 16m"): "wire",
    ("Langdraht", "LW 18m"): "wire",
    ("Langdraht", "LW 20m"): "wire",
    ("Langdraht", "LW 30m"): "wire",
    ("Langdraht", "LW 40m"): "wire",
    ("Langdraht", "LW 60m"): "wire",
    ("Langdraht", "LW 80m"): "wire",
    ("Langdraht", "LW 8m"): "wire",
    # Yagi
    ("Allgemei", "Yagi-3El"): "yagi",
    ("Allgemein", "HB9CV"): "yagi",
    ("Allgemein", "Helix"): "yagi",
    ("Allgemein", "Helix-2"): "yagi",
    ("Allgemein", "Yagi-2El"): "yagi",
    ("Allgemein", "Yagi-4El"): "yagi",
    ("Allgemein", "Yagi-5El"): "yagi",
    ("Allgemein", "Yagi-6El"): "yagi",
    ("Allgemein", "Yagi-7El"): "yagi",
    ("Allgemein", "Yagi-8El"): "yagi",
    ("Barker & Williamson", "BWD-90"): "yagi",
    ("Butterfly", "HF-5"): "yagi",
    ("Comet", "CA-52HB4"): "yagi",
    ("Cush-Craft", "R8"): "yagi",
    ("Cush-Craft", "XM510"): "yagi",
    ("Cush-Craft", "XM515"): "yagi",
    ("Cush-Craft", "XM520"): "yagi",
    ("Cush_Craft", "X7"): "yagi",
    ("Cushcraft", "10-3CD"): "yagi",
    ("Cushcraft", "124WB"): "yagi",
    ("Cushcraft", "13B2N"): "yagi",
    ("Cushcraft", "15-4CD"): "yagi",
    ("Cushcraft", "20-4CD"): "yagi",
    ("Cushcraft", "40-2CD"): "yagi",
    ("Cushcraft", "719B"): "yagi",
    ("Cushcraft", "729B"): "yagi",
    ("Cushcraft", "A-3-S"): "yagi",
    ("Cushcraft", "A-3-WS"): "yagi",
    ("Cushcraft", "A-4-S"): "yagi",
    ("Cushcraft", "A14410SN"): "yagi",
    ("Cushcraft", "A27-10S"): "yagi",
    ("Cushcraft", "A270-6S"): "yagi",
    ("Cushcraft", "A43011N"): "yagi",
    ("Cushcraft", "A50-3S"): "yagi",
    ("Cushcraft", "A50-5S"): "yagi",
    ("Cushcraft", "A503S"): "yagi",
    ("Cushcraft", "A505S"): "yagi",
    ("Cushcraft", "A506S"): "yagi",
    ("DJ2UT", "P5C"): "yagi",
    ("Diamon", "V-2000"): "yagi",
    ("Diamon", "V2000"): "yagi",
    ("Diamond", "G-200"): "yagi",
    ("Eigenbau", "Bi-Square"): "yagi",
    ("Flexa", "2xFX213hor"): "yagi",
    ("Flexa", "2xFX217hor"): "yagi",
    ("Flexa", "2xFx224hor"): "yagi",
    ("Flexa", "2xFx2304horiz"): "yagi",
    ("Flexa", "2xFx2317hor"): "yagi",
    ("Flexa", "4xFX213hor"): "yagi",
    ("Flexa", "4xFx2317hor"): "yagi",
    ("Flexa", "FX1308-V"): "yagi",
    ("Flexa", "FX210"): "yagi",
    ("Flexa", "FX213"): "yagi",
    ("Flexa", "Fx205v"): "yagi",
    ("Flexa", "Fx217"): "yagi",
    ("Flexa", "Fx224"): "yagi",
    ("Flexa", "Fx2304horiz"): "yagi",
    ("Flexa", "Fx2304v"): "yagi",
    ("Flexa", "Fx2309"): "yagi",
    ("Flexa", "Fx2317"): "yagi",
    ("Flexa", "Fx2317hor"): "yagi",
    ("Flexa", "Fx2317vert"): "yagi",
    ("Flexa", "Fx7015v"): "yagi",
    ("Flexa", "Fx7033"): "yagi",
    ("Flexa", "Fx7033hor"): "yagi",
    ("Flexa", "Fx7033vert"): "yagi",
    ("Flexa", "Fx7044"): "yagi",
    ("Flexa", "Fx7044-4"): "yagi",
    ("Flexa", "Fx7056"): "yagi",
    ("Flexa", "Fx7073"): "yagi",
    ("Flexa", "Fx7073hor"): "yagi",
    ("Flexa", "Fx7073vert"): "yagi",
    ("Fritzel", "FB-DX460"): "yagi",
    ("Fritzel", "FB-DX660"): "yagi",
    ("Fritzel", "FB-Do450"): "yagi",
    ("Fritzel", "FB-Do505"): "yagi",
    ("Fritzel", "FB-Dx506"): "yagi",
    ("Fritzel", "FB13"): "yagi",
    ("Fritzel", "FB23"): "yagi",
    ("Fritzel", "FB33"): "yagi",
    ("Fritzel", "FB34"): "yagi",
    ("Fritzel", "FB53"): "yagi",
    ("Fritzel", "MFB23"): "yagi",
    ("Fritzel", "UFB12"): "yagi",
    ("Fritzel", "UFB13"): "yagi",
    ("Fritzel", "UFB33"): "yagi",
    ("Hy-Gain", "103BAS"): "yagi",
    ("Hy-Gain", "105BAS"): "yagi",
    ("Hy-Gain", "155BAS"): "yagi",
    ("Hy-Gain", "204BAS"): "yagi",
    ("Hy-Gain", "205BAS"): "yagi",
    ("Hy-Gain", "AV-640"): "yagi",
    ("Hy-Gain", "CA-2x4max"): "yagi",
    ("Hy-Gain", "TH11DX"): "yagi",
    ("Hy-Gain", "TH2Mk3"): "yagi",
    ("Hy-Gain", "TH3JRS"): "yagi",
    ("Hy-Gain", "TH3Mk3"): "yagi",
    ("Hy-Gain", "TH5Mk2"): "yagi",
    ("Hy-Gain", "TH6DXX"): "yagi",
    ("Hy-Gain", "TH7DX"): "yagi",
    ("KLM", "KT-34A"): "yagi",
    ("KLM", "KT-34XA"): "yagi",
    ("Maspr", "WHS-32N"): "yagi",
    ("Maspro", "WH-59hor"): "yagi",
    ("Maspro", "WH-59vert"): "yagi",
    ("Mosle", "TA-33M"): "yagi",
    ("Mosle", "TA-33M warc"): "yagi",
    ("Mosle", "TA-33jrn warc"): "yagi",
    ("Mosle", "TA-34xl"): "yagi",
    ("Mosle", "TA-34xl warc"): "yagi",
    ("Mosle", "TW-23M"): "yagi",
    ("Mosle", "TW-24xl"): "yagi",
    ("Mosle", "TW-31xl"): "yagi",
    ("Mosle", "TW-32xl"): "yagi",
    ("Mosle", "TW-33xl"): "yagi",
    ("Mosley", "CL-33-M"): "yagi",
    ("Mosley", "CL-33warc"): "yagi",
    ("Mosley", "CL-36-M"): "yagi",
    ("Mosley", "MP-33N"): "yagi",
    ("Mosley", "MP-33N warc"): "yagi",
    ("Mosley", "Mini-33"): "yagi",
    ("Mosley", "Pro-57B"): "yagi",
    ("Mosley", "Pro-57B-40"): "yagi",
    ("Mosley", "Pro-67A"): "yagi",
    ("Mosley", "Pro-67B"): "yagi",
    ("Mosley", "Pro-67c-3"): "yagi",
    ("Mosley", "Pro-77A"): "yagi",
    ("Mosley", "Pro-95"): "yagi",
    ("Mosley", "Pro-96"): "yagi",
    ("Mosley", "TA-31M"): "yagi",
    ("Mosley", "TA-31jrn"): "yagi",
    ("Mosley", "TA-32M"): "yagi",
    ("Mosley", "TA-32jrn"): "yagi",
    ("Mosley", "TA-33jrn"): "yagi",
    ("Mosley", "TA-53M"): "yagi",
    ("Muehla", "DX2000"): "yagi",
    ("Opti-Beam", "OB10-3W"): "yagi",
    ("Opti-Beam", "OB11-3"): "yagi",
    ("Opti-Beam", "OB11-5"): "yagi",
    ("Opti-Beam", "OB12-4"): "yagi",
    ("Opti-Beam", "OB12-4WARC"): "yagi",
    ("Opti-Beam", "OB13-6"): "yagi",
    ("Opti-Beam", "OB15-7"): "yagi",
    ("Opti-Beam", "OB16-3"): "yagi",
    ("Opti-Beam", "OB16-5"): "yagi",
    ("Opti-Beam", "OB17-4"): "yagi",
    ("Opti-Beam", "OB18-6"): "yagi",
    ("Opti-Beam", "OB2-30"): "yagi",
    ("Opti-Beam", "OB2-40"): "yagi",
    ("Opti-Beam", "OB2-40M"): "yagi",
    ("Opti-Beam", "OB2-80"): "yagi",
    ("Opti-Beam", "OB3-30"): "yagi",
    ("Opti-Beam", "OB3-80"): "yagi",
    ("Opti-Beam", "OB4-2W"): "yagi",
    ("Opti-Beam", "OB4-2WARC"): "yagi",
    ("Opti-Beam", "OB4-40"): "yagi",
    ("Opti-Beam", "OB4020"): "yagi",
    ("Opti-Beam", "OB4030"): "yagi",
    ("Opti-Beam", "OB5-10"): "yagi",
    ("Opti-Beam", "OB5-12"): "yagi",
    ("Opti-Beam", "OB5-15"): "yagi",
    ("Opti-Beam", "OB5-17"): "yagi",
    ("Opti-Beam", "OB5-20"): "yagi",
    ("Opti-Beam", "OB5-6"): "yagi",
    ("Opti-Beam", "OB6-10"): "yagi",
    ("Opti-Beam", "OB6-2WARC"): "yagi",
    ("Opti-Beam", "OB6-3M"): "yagi",
    ("Opti-Beam", "OB6-6"): "yagi",
    ("Opti-Beam", "OB7-2W"): "yagi",
    ("Opti-Beam", "OB7-2WARC"): "yagi",
    ("Opti-Beam", "OB7-3"): "yagi",
    ("Opti-Beam", "OB7-3M"): "yagi",
    ("Opti-Beam", "OB804020"): "yagi",
    ("Opti-Beam", "OB9-2W"): "yagi",
    ("Opti-Beam", "OB9-2WARC"): "yagi",
    ("Opti-Beam", "OB9-5"): "yagi",
    ("Opti-Beam", "OBW10-5"): "yagi",
    ("Optibeam", "OB12-6"): "yagi",
    ("Optibeam", "OB8-4M"): "yagi",
    ("Optibeam", "OB8_4M"): "yagi",
    ("SHF", "SHF1340"): "yagi",
    ("SHF", "SHF1367"): "yagi",
    ("SHF", "SHF2328"): "yagi",
    ("SHF", "SHF2344"): "yagi",
    ("SHF", "SHF2367"): "yagi",
    ("Somme", "XP406"): "yagi",
    ("Somme", "XP507"): "yagi",
    ("Somme", "XP707"): "yagi",
    ("Somme", "XP807"): "yagi",
    ("SteppIR", "SteppIR_2El"): "yagi",
    ("SteppIR", "SteppIR_3El"): "yagi",
    ("SteppIR", "SteppIR_4El"): "yagi",
    ("SteppIR", "Stepp_3El"): "yagi",
    ("Tonna", "20089"): "yagi",
    ("Tonna", "20505"): "yagi",
    ("Tonna", "20623"): "yagi",
    ("Tonna", "20624"): "yagi",
    ("Tonna", "20635"): "yagi",
    ("Tonna", "20636"): "yagi",
    ("Tonna", "20650"): "yagi",
    ("Tonna", "20655"): "yagi",
    ("Tonna", "20725"): "yagi",
    ("Tonna", "20804"): "yagi",
    ("Tonna", "20808"): "yagi",
    ("Tonna", "20809"): "yagi",
    ("Tonna", "20813"): "yagi",
    ("Tonna", "20818"): "yagi",
    ("Tonna", "20919"): "yagi",
    ("Tonna", "20922"): "yagi",
    ("Tonna", "F9FT-horiz"): "yagi",
    ("Tonna", "F9FT-vert"): "yagi",
    ("Tonna", "T-17El-horiz"): "yagi",
    ("Tonna", "T-17El-vert"): "yagi",
    ("Tonna", "T-4x17El-horiz"): "yagi",
    ("Tonna", "T-4x17El-vert"): "yagi",
    ("Wimo", "D2T"): "yagi",
    ("Wimo", "Wx208"): "yagi",
    ("Wimo", "Wx214"): "yagi",
    ("Wimo", "Wx220"): "yagi",
    ("Wimo", "Wx7020"): "yagi",
    ("Wimo", "Wx7036"): "yagi",
    ("Wimo", "Wy204"): "yagi",
    ("Wimo", "Wy207"): "yagi",
    ("Wimo", "Wy210"): "yagi",
    ("Wimo", "Wy7010"): "yagi",
    ("Wimo", "Wy7018"): "yagi",
    ("Wimo", "Wy7023"): "yagi",
    ("Wimo", "Wy706"): "yagi",
    ("Wimo", "ZX6-2"): "yagi",
}

# Read the JSON file
with open('src/NIS.Core/Resources/antennas.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Track counts and unmatched
counts = {
    "log-periodic": 0,
    "loop": 0,
    "other": 0,
    "quad": 0,
    "vertical": 0,
    "wire": 0,
    "yagi": 0
}
unmatched = []
matched = 0

# Process each antenna
for antenna in data['antennas']:
    manufacturer = antenna['manufacturer']
    model = antenna['model']
    key = (manufacturer, model)

    if key in classifications:
        antenna['antennaType'] = classifications[key]
        counts[classifications[key]] += 1
        matched += 1
    else:
        # Keep existing or set to other
        if 'antennaType' not in antenna:
            antenna['antennaType'] = 'other'
        unmatched.append(f"{manufacturer} | {model}")
        counts[antenna['antennaType']] += 1

# Write updated JSON
with open('src/NIS.Core/Resources/antennas.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

# Print summary
print("Classification Applied:")
print("=" * 40)
for t in sorted(counts.keys()):
    print(f"  {t}: {counts[t]}")
print(f"  {'='*20}")
print(f"  Total: {sum(counts.values())}")
print(f"\nMatched from provided list: {matched}")
print(f"Not in provided list: {len(unmatched)}")

if unmatched:
    print(f"\nAntennas not in provided list (kept existing type):")
    for u in unmatched:
        print(f"  {u}")
